-- ==============================================================================
-- VOCABLY - SUPABASE POSTGRESQL SCHEMA & RLS POLICIES
-- ==============================================================================

-- 1. BẢNG HỒ SƠ NGƯỜI DÙNG (PROFILES)
-- Liên kết trực tiếp với auth.users của Supabase
create table if not exists public.profiles (
  id uuid references auth.users(id) on delete cascade primary key,
  email text not null,
  name text not null,
  role text not null default 'user' check (role in ('user', 'admin')),
  target_score int default 850,
  avatar text default 'V',
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

-- Trigger tự động tạo hồ sơ profile khi có user đăng ký tài khoản mới qua Supabase Auth
create or replace function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, email, name, role, target_score, avatar)
  values (
    new.id,
    new.email,
    coalesce(new.raw_user_meta_data->>'name', split_part(new.email, '@', 1)),
    coalesce(new.raw_user_meta_data->>'role', 'user'),
    coalesce((new.raw_user_meta_data->>'targetScore')::int, 850),
    upper(substring(coalesce(new.raw_user_meta_data->>'name', 'V') from 1 for 1))
  );
  return new;
end;
$$ language plpgsql security definer;

-- Drop trigger nếu đã tồn tại để tránh trùng lặp
drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- 2. BẢNG KHO TỪ VỰNG (WORDS)
-- Chứa cả từ vựng seed hệ thống (is_seed = true) và từ vựng riêng của người dùng
create table if not exists public.words (
  id bigint generated by default as identity primary key,
  word text not null,
  ipa text default '',
  meaning text not null,
  part_of_speech text default 'noun',
  topic text default 'General',
  example text default '',
  tags text[] default '{}',
  is_seed boolean default false,
  user_id uuid references auth.users(id) on delete cascade,
  created_at timestamptz default now()
);

create index if not exists idx_words_topic on public.words(topic);
create index if not exists idx_words_is_seed on public.words(is_seed);
create index if not exists idx_words_user_id on public.words(user_id);

-- 3. BẢNG TIẾN ĐỘ THUẬT TOÁN FSRS CỦA NGƯỜI DÙNG (USER_WORD_PROGRESS)
create table if not exists public.user_word_progress (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  word_id bigint references public.words(id) on delete cascade not null,
  status text not null default 'new' check (status in ('new', 'learning', 'review', 'known')),
  next_review timestamptz default now(),
  stability float default 0,
  difficulty float default 5,
  elapsed_days int default 0,
  scheduled_days int default 0,
  reps int default 0,
  lapses int default 0,
  fsrs_state int default 0,
  last_review timestamptz,
  updated_at timestamptz default now(),
  unique(user_id, word_id)
);

create index if not exists idx_progress_user_next on public.user_word_progress(user_id, next_review);
create index if not exists idx_progress_status on public.user_word_progress(user_id, status);

-- 4. BẢNG LỊCH SỬ PHIÊN HỌC (STUDY_SESSIONS)
create table if not exists public.study_sessions (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  date date not null default current_date,
  mode text not null,
  words_studied int not null default 0,
  correct int not null default 0,
  created_at timestamptz default now()
);

create index if not exists idx_sessions_user_date on public.study_sessions(user_id, date);

-- ==============================================================================
-- 5. BẢO MẬT & PHÂN QUYỀN VỚI ROW LEVEL SECURITY (RLS)
-- ==============================================================================

alter table public.profiles enable row level security;
alter table public.words enable row level security;
alter table public.user_word_progress enable row level security;
alter table public.study_sessions enable row level security;

-- PROFILES POLICIES
create policy "Users can view their own profile"
  on public.profiles for select
  using (auth.uid() = id or (select role from public.profiles where id = auth.uid()) = 'admin');

create policy "Users can update their own profile"
  on public.profiles for update
  using (auth.uid() = id);

-- WORDS POLICIES
-- Mọi người có thể xem từ hệ thống hoặc từ của chính mình
create policy "Anyone can view seed words or own words"
  on public.words for select
  using (is_seed = true or auth.uid() = user_id or (select role from public.profiles where id = auth.uid()) = 'admin');

create policy "Users can insert their own words"
  on public.words for insert
  with check (auth.uid() = user_id and is_seed = false);

create policy "Users can update their own words"
  on public.words for update
  using (auth.uid() = user_id and is_seed = false);

create policy "Users can delete their own words"
  on public.words for delete
  using (auth.uid() = user_id and is_seed = false);

create policy "Admins can manage all words"
  on public.words for all
  using ((select role from public.profiles where id = auth.uid()) = 'admin');

-- USER_WORD_PROGRESS POLICIES
create policy "Users can view their own word progress"
  on public.user_word_progress for select
  using (auth.uid() = user_id);

create policy "Users can insert their own word progress"
  on public.user_word_progress for insert
  with check (auth.uid() = user_id);

create policy "Users can update their own word progress"
  on public.user_word_progress for update
  using (auth.uid() = user_id);

-- STUDY_SESSIONS POLICIES
create policy "Users can view their own study sessions"
  on public.study_sessions for select
  using (auth.uid() = user_id or (select role from public.profiles where id = auth.uid()) = 'admin');

create policy "Users can insert their own study sessions"
  on public.study_sessions for insert
  with check (auth.uid() = user_id);
