/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppAdminRouteImport } from './routes/_app/admin'
import { Route as AppDashboardRouteImport } from './routes/_app/dashboard'
import { Route as AppSettingsRouteImport } from './routes/_app/settings'
import { Route as AppStudyRouteImport } from './routes/_app/study'
import { Route as AppWordsRouteImport } from './routes/_app/words'
import { Route as AppStudyIndexRouteImport } from './routes/_app/study.index'
import { Route as AppStudyFillRouteImport } from './routes/_app/study.fill'
import { Route as AppStudyFlashcardRouteImport } from './routes/_app/study.flashcard'
import { Route as AppStudyQuizRouteImport } from './routes/_app/study.quiz'
import { Route as AppStudySpellingRouteImport } from './routes/_app/study.spelling'
import { Route as AppWordsIndexRouteImport } from './routes/_app/words.index'
import { Route as AppWordsAddRouteImport } from './routes/_app/words.add'
import { Route as AppWordsEditIdRouteImport } from './routes/_app/words.edit.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyRoute = AppStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => AppRoute,
} as any)
const AppWordsRoute = AppWordsRouteImport.update({
  id: '/words',
  path: '/words',
  getParentRoute: () => AppRoute,
} as any)
const AppStudyIndexRoute = AppStudyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppStudyRoute,
} as any)
const AppStudyFillRoute = AppStudyFillRouteImport.update({
  id: '/fill',
  path: '/fill',
  getParentRoute: () => AppStudyRoute,
} as any)
const AppStudyFlashcardRoute = AppStudyFlashcardRouteImport.update({
  id: '/flashcard',
  path: '/flashcard',
  getParentRoute: () => AppStudyRoute,
} as any)
const AppStudyQuizRoute = AppStudyQuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => AppStudyRoute,
} as any)
const AppStudySpellingRoute = AppStudySpellingRouteImport.update({
  id: '/spelling',
  path: '/spelling',
  getParentRoute: () => AppStudyRoute,
} as any)
const AppWordsIndexRoute = AppWordsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppWordsRoute,
} as any)
const AppWordsAddRoute = AppWordsAddRouteImport.update({
  id: '/add',
  path: '/add',
  getParentRoute: () => AppWordsRoute,
} as any)
const AppWordsEditIdRoute = AppWordsEditIdRouteImport.update({
  id: '/edit/$id',
  path: '/edit/$id',
  getParentRoute: () => AppWordsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/study': typeof AppStudyRouteWithChildren
  '/words': typeof AppWordsRouteWithChildren
  '/study/fill': typeof AppStudyFillRoute
  '/study/flashcard': typeof AppStudyFlashcardRoute
  '/study/quiz': typeof AppStudyQuizRoute
  '/study/spelling': typeof AppStudySpellingRoute
  '/words/add': typeof AppWordsAddRoute
  '/study/': typeof AppStudyIndexRoute
  '/words/': typeof AppWordsIndexRoute
  '/words/edit/$id': typeof AppWordsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AppAdminRoute
  '/dashboard': typeof AppDashboardRoute
  '/settings': typeof AppSettingsRoute
  '/study/fill': typeof AppStudyFillRoute
  '/study/flashcard': typeof AppStudyFlashcardRoute
  '/study/quiz': typeof AppStudyQuizRoute
  '/study/spelling': typeof AppStudySpellingRoute
  '/words/add': typeof AppWordsAddRoute
  '/study': typeof AppStudyIndexRoute
  '/words': typeof AppWordsIndexRoute
  '/words/edit/$id': typeof AppWordsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/study': typeof AppStudyRouteWithChildren
  '/_app/words': typeof AppWordsRouteWithChildren
  '/_app/study/fill': typeof AppStudyFillRoute
  '/_app/study/flashcard': typeof AppStudyFlashcardRoute
  '/_app/study/quiz': typeof AppStudyQuizRoute
  '/_app/study/spelling': typeof AppStudySpellingRoute
  '/_app/words/add': typeof AppWordsAddRoute
  '/_app/study/': typeof AppStudyIndexRoute
  '/_app/words/': typeof AppWordsIndexRoute
  '/_app/words/edit/$id': typeof AppWordsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/study'
    | '/words'
    | '/study/fill'
    | '/study/flashcard'
    | '/study/quiz'
    | '/study/spelling'
    | '/words/add'
    | '/study/'
    | '/words/'
    | '/words/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin'
    | '/dashboard'
    | '/settings'
    | '/study/fill'
    | '/study/flashcard'
    | '/study/quiz'
    | '/study/spelling'
    | '/words/add'
    | '/study'
    | '/words'
    | '/words/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/admin'
    | '/_app/dashboard'
    | '/_app/settings'
    | '/_app/study'
    | '/_app/words'
    | '/_app/study/fill'
    | '/_app/study/flashcard'
    | '/_app/study/quiz'
    | '/_app/study/spelling'
    | '/_app/words/add'
    | '/_app/study/'
    | '/_app/words/'
    | '/_app/words/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/study': {
      id: '/_app/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof AppStudyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/words': {
      id: '/_app/words'
      path: '/words'
      fullPath: '/words'
      preLoaderRoute: typeof AppWordsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/study/': {
      id: '/_app/study/'
      path: '/'
      fullPath: '/study/'
      preLoaderRoute: typeof AppStudyIndexRouteImport
      parentRoute: typeof AppStudyRoute
    }
    '/_app/study/fill': {
      id: '/_app/study/fill'
      path: '/fill'
      fullPath: '/study/fill'
      preLoaderRoute: typeof AppStudyFillRouteImport
      parentRoute: typeof AppStudyRoute
    }
    '/_app/study/flashcard': {
      id: '/_app/study/flashcard'
      path: '/flashcard'
      fullPath: '/study/flashcard'
      preLoaderRoute: typeof AppStudyFlashcardRouteImport
      parentRoute: typeof AppStudyRoute
    }
    '/_app/study/quiz': {
      id: '/_app/study/quiz'
      path: '/quiz'
      fullPath: '/study/quiz'
      preLoaderRoute: typeof AppStudyQuizRouteImport
      parentRoute: typeof AppStudyRoute
    }
    '/_app/study/spelling': {
      id: '/_app/study/spelling'
      path: '/spelling'
      fullPath: '/study/spelling'
      preLoaderRoute: typeof AppStudySpellingRouteImport
      parentRoute: typeof AppStudyRoute
    }
    '/_app/words/': {
      id: '/_app/words/'
      path: '/'
      fullPath: '/words/'
      preLoaderRoute: typeof AppWordsIndexRouteImport
      parentRoute: typeof AppWordsRoute
    }
    '/_app/words/add': {
      id: '/_app/words/add'
      path: '/add'
      fullPath: '/words/add'
      preLoaderRoute: typeof AppWordsAddRouteImport
      parentRoute: typeof AppWordsRoute
    }
    '/_app/words/edit/$id': {
      id: '/_app/words/edit/$id'
      path: '/edit/$id'
      fullPath: '/words/edit/$id'
      preLoaderRoute: typeof AppWordsEditIdRouteImport
      parentRoute: typeof AppWordsRoute
    }
  }
}

interface AppStudyRouteChildren {
  AppStudyFillRoute: typeof AppStudyFillRoute
  AppStudyFlashcardRoute: typeof AppStudyFlashcardRoute
  AppStudyQuizRoute: typeof AppStudyQuizRoute
  AppStudySpellingRoute: typeof AppStudySpellingRoute
  AppStudyIndexRoute: typeof AppStudyIndexRoute
}

const AppStudyRouteChildren: AppStudyRouteChildren = {
  AppStudyFillRoute: AppStudyFillRoute,
  AppStudyFlashcardRoute: AppStudyFlashcardRoute,
  AppStudyQuizRoute: AppStudyQuizRoute,
  AppStudySpellingRoute: AppStudySpellingRoute,
  AppStudyIndexRoute: AppStudyIndexRoute,
}

const AppStudyRouteWithChildren = AppStudyRoute._addFileChildren(
  AppStudyRouteChildren,
)

interface AppWordsRouteChildren {
  AppWordsAddRoute: typeof AppWordsAddRoute
  AppWordsIndexRoute: typeof AppWordsIndexRoute
  AppWordsEditIdRoute: typeof AppWordsEditIdRoute
}

const AppWordsRouteChildren: AppWordsRouteChildren = {
  AppWordsAddRoute: AppWordsAddRoute,
  AppWordsIndexRoute: AppWordsIndexRoute,
  AppWordsEditIdRoute: AppWordsEditIdRoute,
}

const AppWordsRouteWithChildren = AppWordsRoute._addFileChildren(
  AppWordsRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppStudyRoute: typeof AppStudyRouteWithChildren
  AppWordsRoute: typeof AppWordsRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppStudyRoute: AppStudyRouteWithChildren,
  AppWordsRoute: AppWordsRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
